language: python

matrix:
  include:
    - os: osx
      sudo: false
      python: "3.6"
 
    - os: linux
      dist: trusty
      sudo: false
      python: "2.7"

# install dependencies
before_install:
    - if test ${TRAVIS_OS_NAME} = "osx"; then
        brew update;
        brew install gcc;
      fi

    - if test ${TRAVIS_OS_NAME} = "linux"; then
        python -c "import  ctypes; print ctypes.__version__";
        git clone https://github.com/stoiver/Stormwater-Management-Model.git ;
        pushd Stormwater-Management-Model;
        git pull;
        git checkout toolkitapi;
        pushd build;
        mkdir buildproducts;
        pushd buildproducts;
        cmake ..;
        make;
        ls -l bin;
        ls -l /home/travis/build/OpenWaterAnalytics/pyswmm/pyswmm/lib/linux/;
        mv -f bin/libswmm.so /home/travis/build/OpenWaterAnalytics/pyswmm/pyswmm/lib/linux/swmm5.so ;
        ls -l /home/travis/build/OpenWaterAnalytics/pyswmm/pyswmm/lib/linux/;
        popd;
        popd;
        popd;
      fi

install: 
  - pip install -r requirements-travis.txt
  - python -c "import enum; print enum.version"

script:
  - py.test pyswmm --ignore=pyswmm/tests/test_plot_node_inflows.py

