language: python

matrix:
  include:
    - os: osx
      language: generic
      sudo: false
      python: "2.7"

    - os: osx
      language: generic
      sudo: false
      python: "3.6"
 
    - os: linux
      dist: trusty
      sudo: false
      python: "2.7"

    - os: linux
      dist: trusty
      sudo: false
      python: "3.6"

# install dependencies
before_install:
    - if test ${TRAVIS_OS_NAME} = "osx"; then
        brew update;
        brew install gcc;
      fi
    - if test ${TRAVIS_OS_NAME} = "linux"; then
        export DISPLAY=:99.0;
      fi
install: 
  - pip install -r requirements-travis.txt

script:
  - py.test pyswmm --ignore=pyswmm/tests/test_plot_node_inflows.py --ignore=pyswmm/tests/test_plot_pump_setting.py --ignore=pyswmm/tests/test_plot_toolkit_units.py 

