language: python

matrix:
  include:
    - os: osx
      sudo: false
      python: "3.6"
 
    - os: linux
      dist: trusty
      sudo: false
      python: "2.7"

# install dependencies
before_install:
    - if test ${TRAVIS_OS_NAME} = "osx"; then
        brew update;
        brew install gcc;
      fi

    - if test ${TRAVIS_OS_NAME} = "linux"; then
        python -c "import  ctypes; print ctypes.__version__";
      fi

install: 
  - pip install -r requirements-travis.txt"

script:
  - py.test pyswmm
