

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

install:
  - "%PYTHON%\\python setup.py develop"
  - "%PYTHON%\\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

# Not a .NET project, we build in the install step instead
build: false

test_script:
#  - ciocheck setup.py --disable-tests
#  - ciocheck pyswmm --disable-tests
  - "%PYTHON%\\Scripts\\pytest pyswmm"
#  - coveralls --disable-tests
